version: '3.6'
services:

  backend:
    build:
      context: ../done4fun-api/
  postgres:
    image: postgres:14
#    volumes:
#      - ./docker/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: ufo
      POSTGRES_PASSWORD: "!!!UfO:-)1234!!!"
      POSTGRES_DB: done4fun
      POSTGRES_HOST: postgres
    ports:
      - "5432:5432"
#  web:
#    image: nginx:latest
#    ports:
#      - "8000:80"
#    depends_on:
#      - app
#    volumes:
#      - ./public:/var/www/html/public
#      - ./site.conf:/etc/nginx/conf.d/default.conf:ro
